/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gearet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Gearet#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Gearet#isSystem <em>System</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Gearet#isMarke <em>Marke</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Gearet#isSpeicher <em>Speicher</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGearet()
 * @model
 * @generated
 */
public interface Gearet extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGearet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Gearet#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' attribute.
   * @see #setSystem(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGearet_System()
   * @model
   * @generated
   */
  boolean isSystem();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Gearet#isSystem <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' attribute.
   * @see #isSystem()
   * @generated
   */
  void setSystem(boolean value);

  /**
   * Returns the value of the '<em><b>Marke</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Marke</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Marke</em>' attribute.
   * @see #setMarke(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGearet_Marke()
   * @model
   * @generated
   */
  boolean isMarke();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Gearet#isMarke <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Marke</em>' attribute.
   * @see #isMarke()
   * @generated
   */
  void setMarke(boolean value);

  /**
   * Returns the value of the '<em><b>Speicher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speicher</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speicher</em>' attribute.
   * @see #setSpeicher(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGearet_Speicher()
   * @model
   * @generated
   */
  boolean isSpeicher();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Gearet#isSpeicher <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speicher</em>' attribute.
   * @see #isSpeicher()
   * @generated
   */
  void setSpeicher(boolean value);

} // Gearet
