/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/vertrag/Vertrag";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Vertrags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VERTRAGS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VertragImpl <em>Vertrag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VertragImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVertrag()
   * @generated
   */
  int VERTRAG = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__NAME = 0;

  /**
   * The feature id for the '<em><b>Mindestvertragslaufzeit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__MINDESTVERTRAGSLAUFZEIT = 1;

  /**
   * The feature id for the '<em><b>Datenvolumen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__DATENVOLUMEN = 2;

  /**
   * The feature id for the '<em><b>Monatl kosten</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__MONATL_KOSTEN = 3;

  /**
   * The feature id for the '<em><b>Netzanbieter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__NETZANBIETER = 4;

  /**
   * The feature id for the '<em><b>Internetseite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__INTERNETSEITE = 5;

  /**
   * The number of structural features of the '<em>Vertrag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl <em>Gearet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GearetImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGearet()
   * @generated
   */
  int GEARET = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEARET__NAME = 0;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEARET__SYSTEM = 1;

  /**
   * The feature id for the '<em><b>Marke</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEARET__MARKE = 2;

  /**
   * The feature id for the '<em><b>Speicher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEARET__SPEICHER = 3;

  /**
   * The number of structural features of the '<em>Gearet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEARET_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getVertrags <em>Vertrags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vertrags</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getVertrags()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Vertrags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Vertrag <em>Vertrag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertrag</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag
   * @generated
   */
  EClass getVertrag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getName()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getMindestvertragslaufzeit <em>Mindestvertragslaufzeit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mindestvertragslaufzeit</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getMindestvertragslaufzeit()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Mindestvertragslaufzeit();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getDatenvolumen <em>Datenvolumen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datenvolumen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getDatenvolumen()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Datenvolumen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getMonatl_kosten <em>Monatl kosten</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Monatl kosten</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getMonatl_kosten()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Monatl_kosten();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getNetzanbieter <em>Netzanbieter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Netzanbieter</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getNetzanbieter()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Netzanbieter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vertrag#getInternetseite <em>Internetseite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Internetseite</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vertrag#getInternetseite()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Internetseite();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Gearet <em>Gearet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gearet</em>'.
   * @see org.xtext.example.mydsl.myDsl.Gearet
   * @generated
   */
  EClass getGearet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Gearet#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Gearet#getName()
   * @see #getGearet()
   * @generated
   */
  EAttribute getGearet_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Gearet#isSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>System</em>'.
   * @see org.xtext.example.mydsl.myDsl.Gearet#isSystem()
   * @see #getGearet()
   * @generated
   */
  EAttribute getGearet_System();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Gearet#isMarke <em>Marke</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Marke</em>'.
   * @see org.xtext.example.mydsl.myDsl.Gearet#isMarke()
   * @see #getGearet()
   * @generated
   */
  EAttribute getGearet_Marke();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Gearet#isSpeicher <em>Speicher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speicher</em>'.
   * @see org.xtext.example.mydsl.myDsl.Gearet#isSpeicher()
   * @see #getGearet()
   * @generated
   */
  EAttribute getGearet_Speicher();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Vertrags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__VERTRAGS = eINSTANCE.getModel_Vertrags();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VertragImpl <em>Vertrag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VertragImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVertrag()
     * @generated
     */
    EClass VERTRAG = eINSTANCE.getVertrag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__NAME = eINSTANCE.getVertrag_Name();

    /**
     * The meta object literal for the '<em><b>Mindestvertragslaufzeit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__MINDESTVERTRAGSLAUFZEIT = eINSTANCE.getVertrag_Mindestvertragslaufzeit();

    /**
     * The meta object literal for the '<em><b>Datenvolumen</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__DATENVOLUMEN = eINSTANCE.getVertrag_Datenvolumen();

    /**
     * The meta object literal for the '<em><b>Monatl kosten</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__MONATL_KOSTEN = eINSTANCE.getVertrag_Monatl_kosten();

    /**
     * The meta object literal for the '<em><b>Netzanbieter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__NETZANBIETER = eINSTANCE.getVertrag_Netzanbieter();

    /**
     * The meta object literal for the '<em><b>Internetseite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__INTERNETSEITE = eINSTANCE.getVertrag_Internetseite();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl <em>Gearet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GearetImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGearet()
     * @generated
     */
    EClass GEARET = eINSTANCE.getGearet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEARET__NAME = eINSTANCE.getGearet_Name();

    /**
     * The meta object literal for the '<em><b>System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEARET__SYSTEM = eINSTANCE.getGearet_System();

    /**
     * The meta object literal for the '<em><b>Marke</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEARET__MARKE = eINSTANCE.getGearet_Marke();

    /**
     * The meta object literal for the '<em><b>Speicher</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEARET__SPEICHER = eINSTANCE.getGearet_Speicher();

  }

} //MyDslPackage
