/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Gearet;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gearet</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl#isSystem <em>System</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl#isMarke <em>Marke</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GearetImpl#isSpeicher <em>Speicher</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GearetImpl extends MinimalEObjectImpl.Container implements Gearet
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isSystem() <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSystem()
   * @generated
   * @ordered
   */
  protected static final boolean SYSTEM_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSystem() <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSystem()
   * @generated
   * @ordered
   */
  protected boolean system = SYSTEM_EDEFAULT;

  /**
   * The default value of the '{@link #isMarke() <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMarke()
   * @generated
   * @ordered
   */
  protected static final boolean MARKE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMarke() <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMarke()
   * @generated
   * @ordered
   */
  protected boolean marke = MARKE_EDEFAULT;

  /**
   * The default value of the '{@link #isSpeicher() <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpeicher()
   * @generated
   * @ordered
   */
  protected static final boolean SPEICHER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSpeicher() <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpeicher()
   * @generated
   * @ordered
   */
  protected boolean speicher = SPEICHER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GearetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.GEARET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GEARET__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSystem()
  {
    return system;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSystem(boolean newSystem)
  {
    boolean oldSystem = system;
    system = newSystem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GEARET__SYSTEM, oldSystem, system));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isMarke()
  {
    return marke;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMarke(boolean newMarke)
  {
    boolean oldMarke = marke;
    marke = newMarke;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GEARET__MARKE, oldMarke, marke));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSpeicher()
  {
    return speicher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpeicher(boolean newSpeicher)
  {
    boolean oldSpeicher = speicher;
    speicher = newSpeicher;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GEARET__SPEICHER, oldSpeicher, speicher));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.GEARET__NAME:
        return getName();
      case MyDslPackage.GEARET__SYSTEM:
        return isSystem();
      case MyDslPackage.GEARET__MARKE:
        return isMarke();
      case MyDslPackage.GEARET__SPEICHER:
        return isSpeicher();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.GEARET__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.GEARET__SYSTEM:
        setSystem((Boolean)newValue);
        return;
      case MyDslPackage.GEARET__MARKE:
        setMarke((Boolean)newValue);
        return;
      case MyDslPackage.GEARET__SPEICHER:
        setSpeicher((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GEARET__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.GEARET__SYSTEM:
        setSystem(SYSTEM_EDEFAULT);
        return;
      case MyDslPackage.GEARET__MARKE:
        setMarke(MARKE_EDEFAULT);
        return;
      case MyDslPackage.GEARET__SPEICHER:
        setSpeicher(SPEICHER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GEARET__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.GEARET__SYSTEM:
        return system != SYSTEM_EDEFAULT;
      case MyDslPackage.GEARET__MARKE:
        return marke != MARKE_EDEFAULT;
      case MyDslPackage.GEARET__SPEICHER:
        return speicher != SPEICHER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", system: ");
    result.append(system);
    result.append(", marke: ");
    result.append(marke);
    result.append(", speicher: ");
    result.append(speicher);
    result.append(')');
    return result.toString();
  }

} //GearetImpl
