/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Vertrag_RightCurlyBracketKeyword_5_a;
	protected AbstractElementAlias match_Vertrag_RightCurlyBracketKeyword_5_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_Vertrag_RightCurlyBracketKeyword_5_a = new TokenAlias(true, true, grammarAccess.getVertragAccess().getRightCurlyBracketKeyword_5());
		match_Vertrag_RightCurlyBracketKeyword_5_p = new TokenAlias(true, false, grammarAccess.getVertragAccess().getRightCurlyBracketKeyword_5());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Vertrag_RightCurlyBracketKeyword_5_a.equals(syntax))
				emit_Vertrag_RightCurlyBracketKeyword_5_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Vertrag_RightCurlyBracketKeyword_5_p.equals(syntax))
				emit_Vertrag_RightCurlyBracketKeyword_5_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '}'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'Vertrag' name=ID
	 *     (rule start) (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     (rule start) (ambiguity) 'internetseite' internetseite=ID
	 *     (rule start) (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     (rule start) (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     (rule start) (ambiguity) (rule start)
	 *     datenvolumen=INT (ambiguity) 'Vertrag' name=ID
	 *     datenvolumen=INT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     datenvolumen=INT (ambiguity) 'internetseite' internetseite=ID
	 *     datenvolumen=INT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     datenvolumen=INT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     datenvolumen=INT (ambiguity) (rule end)
	 *     internetseite=ID (ambiguity) 'Vertrag' name=ID
	 *     internetseite=ID (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     internetseite=ID (ambiguity) 'internetseite' internetseite=ID
	 *     internetseite=ID (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     internetseite=ID (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     internetseite=ID (ambiguity) (rule end)
	 *     mindestvertragslaufzeit=INT (ambiguity) 'Vertrag' name=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     mindestvertragslaufzeit=INT (ambiguity) 'internetseite' internetseite=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     mindestvertragslaufzeit=INT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) (rule end)
	 *     monatl_kosten=FLOAT (ambiguity) 'Vertrag' name=ID
	 *     monatl_kosten=FLOAT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     monatl_kosten=FLOAT (ambiguity) 'internetseite' internetseite=ID
	 *     monatl_kosten=FLOAT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     monatl_kosten=FLOAT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     monatl_kosten=FLOAT (ambiguity) (rule end)
	 *     name=ID '{' (ambiguity) 'Vertrag' name=ID
	 *     name=ID '{' (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     name=ID '{' (ambiguity) 'internetseite' internetseite=ID
	 *     name=ID '{' (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     name=ID '{' (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     name=ID '{' (ambiguity) (rule end)
	 *     netzanbieter=ID (ambiguity) 'Vertrag' name=ID
	 *     netzanbieter=ID (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     netzanbieter=ID (ambiguity) 'internetseite' internetseite=ID
	 *     netzanbieter=ID (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     netzanbieter=ID (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     netzanbieter=ID (ambiguity) (rule end)
	 */
	protected void emit_Vertrag_RightCurlyBracketKeyword_5_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Vertrag_RightCurlyBracketKeyword_5_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
