/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.Gearet;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Vertrag;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.GEARET:
				sequence_Gearet(context, (Gearet) semanticObject); 
				return; 
			case MyDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MyDslPackage.VERTRAG:
				sequence_Vertrag(context, (Vertrag) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Gearet returns Gearet
	 *
	 * Constraint:
	 *     (name=ID system?=ID marke?=ID speicher?=ID)
	 */
	protected void sequence_Gearet(ISerializationContext context, Gearet semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.GEARET__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.GEARET__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.GEARET__SYSTEM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.GEARET__SYSTEM));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.GEARET__MARKE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.GEARET__MARKE));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.GEARET__SPEICHER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.GEARET__SPEICHER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGearetAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getGearetAccess().getSystemIDTerminalRuleCall_3_0(), semanticObject.isSystem());
		feeder.accept(grammarAccess.getGearetAccess().getMarkeIDTerminalRuleCall_4_0(), semanticObject.isMarke());
		feeder.accept(grammarAccess.getGearetAccess().getSpeicherIDTerminalRuleCall_5_0(), semanticObject.isSpeicher());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     vertrags+=Vertrag+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Vertrag returns Vertrag
	 *
	 * Constraint:
	 *     ((datenvolumen=INT | monatl_kosten=FLOAT | netzanbieter=ID | internetseite=ID)? (name=ID mindestvertragslaufzeit=INT*)?)+
	 */
	protected void sequence_Vertrag(ISerializationContext context, Vertrag semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
